# Generated by Django 5.1 on 2024-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title', max_length=255)),
                ('description', models.TextField(default='No description')),
            ],
        ),
    ]
